name: cover

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: cover
        run: |
          cd JavaScript
          npm install
          cd scripts
          bash build.sh
          cd ../../DotNet
          dotnet workload restore
          mkdir .nuget
          dotnet build -c Release Bootsharp.Generator
          dotnet pack Bootsharp.Common -c Release -o .nuget
          dotnet build -c Release
          dotnet pack Bootsharp -c Release -o .nuget
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          cd ../JavaScript/scripts
          bash compile-test.sh
          cd ..
          npm run test
      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
