name: cover

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cover:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: cover
        run: |
          cd JavaScript
          npm install
          npm install -g typescript
          cd scripts
          bash build.sh
          cd ../../DotNet
          dotnet workload restore
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          dotnet pack -c Release -o bin
          cd ../JavaScript/scripts
          bash compile-test.sh
          cd ..
          npm run test
          # npm install -g nyc
          # nyc --reporter=lcov npm run test
      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
