name: cover

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: cover
      run: |
          dotnet test DotNet/DotNetJS.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          cd JavaScript/dotnet-runtime
          npm install
          npm run build
          dotnet publish test/csharp/Test.sln
          npm install -g codecov
          npm install -g nyc
          nyc --reporter=lcov -x **/native -x **/bin npm run test
          cd ../..
          codecov
