name: cover

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: cover
      run: |
          dotnet restore Packer/Packer.csproj
          dotnet publish DotNetJS/DotNetJS.csproj -c Release
          cd Runtime
          npm install
          npm run build
          dotnet publish test/project/Test.csproj -c Release
          npm install -g codecov
          npm install -g nyc
          nyc --reporter=lcov -x **/native -x **/bin npm run test
          codecov
