name: package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: package
        run: |
          cd src/js
          npm install
          bash scripts/build.sh
          cd ../cs
          dotnet workload restore
          mkdir .nuget
          dotnet build Bootsharp.Generate -c Release
          dotnet build Bootsharp.Common -c Release
          dotnet pack Bootsharp.Common -o .nuget -c Release
          dotnet pack Bootsharp.Inject -o .nuget -c Release
          dotnet build -c Release
          dotnet pack Bootsharp -o .nuget -c Release
      - name: publish to nuget
        run: |
          dotnet nuget push "src/cs/.nuget/Bootsharp*.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://www.nuget.org --skip-duplicate
      - name: publish to github
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/elringus/index.json -n github --username Elringus --password ${{ secrets.GH_KEY }} --store-password-in-clear-text
          dotnet nuget push "src/cs/.nuget/Bootsharp*.nupkg" -s github -k ${{ secrets.GH_KEY }} --skip-duplicate
