name: publish package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: build
        run: |
          dotnet build DotNet/DotNetJS.sln
          cd JavaScript
          npm ci
          npm run build
      - name: package
        run: |
          cd ../DotNet
          dotnet pack -c Release -o packages
      - name: publish to nuget
        run: |
          dotnet nuget push "./packages/*.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://www.nuget.org
      - name: publish to github
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/Elringus/index.json -n github --username Elringus --password ${{ secrets.GH_KEY }} --store-password-in-clear-text
          dotnet nuget push "./packages/*.nupkg" -s github
